### ISSUE TITLE
Speed up `useGetColonyActionsQuery`

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyCDapp#412] opened 2023-04-14 11:01 UTC
This is the query inside `usePaginatedActions` that gets the actions for the actions list.

Currently we set the network policy on this query to "network-only", which ensures that it gets updated when a new action is created. 

However, this means we can't access the cache at all, so every time the `ActionsList`  gets remounted, we have to refetch the actions from the network (slow). 

This issue is to think about how we can use the cache, while ensuring it contains uptodate data. 

My first thought is to do a network-only refetch of the  `useGetColonyActionsQuery` from the ActionDetailsPage, such that it has the latest data cached when it's remounted. But this might be awkward, because we'd need to pass the refetch function between components (might be able to implement  a special `context` here) -> Apollo doesn't appear to expose a refetch api on queries like it does on mutations.  You only get the refetch function from the query itself: you can't fetch query A from query B.

Second thought is to do some manual configuration of the cache, such that we add the newly created action to the actions list data. 

Other ideas welcome.

**Comment by willm30** [comment] 2023-04-14 11:03
@jakubcolony Tagging you here as you might also have thought about this. I've noticed while filtering out unstaked motions from the actions list how slow the query is. So I started thinking about how we might be able to take advantage of apollo's cache to make it instant, instead of refetching over the network every time.

**Comment by jakubcolony** [comment] 2023-04-17 20:42
> My first thought is to do a network-only refetch of the useGetColonyActionsQuery from the ActionDetailsPage, such that it has the latest data cached when it's remounted.

How would that work when, for example, you navigate between other pages (than Action Details Page) and come back to Actions List page? It wouldn't update the results, right?

> But this might be awkward, because we'd need to pass the refetch function between components (might be able to implement a special context here) -> Apollo doesn't appear to expose a refetch api on queries like it does on mutations. You only get the refetch function from the query itself: you can't fetch query A from query B.

I presume this idea includes changing the network policy to something else than `network-only`, right? In which case simply running the query again (wherever than happens) will update the cache (have a look at the Dapp's sagas, e.g. `moveFunds`). Alternatively, Apollo exposes `client.refetchQueries` method: https://www.apollographql.com/docs/react/data/refetching/#clientrefetchqueries

**Comment by willm30** [comment] 2023-04-18 07:35
> It wouldn't update the results, right?

In what context would the list need updating, aside from creating a new action/motion? If we're going for a "live feed", we could still do better than the current approach as I was noticing a few seconds of loading in my dev env every time I came back to Colony Home. In that case, we'd probably want to investigate a subscription instead of a query.

**Comment by jakubcolony** [comment] 2023-04-18 07:51
The foundation of the problem is that we don't know when other users perform actions, hence we play it safe and refetch every time the list is reloaded.

> In that case, we'd probably want to investigate a subscription instead of a query.

Subscriptions put another level of strain on the server. And I'm not sure our use case matches any of the suggested by Apollo docs: https://www.apollographql.com/docs/react/data/subscriptions/#when-to-use-subscriptions

I'd be leaning more towards stale-white-revalidate, or `cache-and-network` fetch policy to be exact. IIRC, I changed it to `network-only` as I couldn't get easily get it to work with custom cache config. I think we should hold off until QA/production and see what's the impact of it there.

**Comment by willm30** [comment] 2023-04-18 07:55
A live feed would satisfy both of their recommendations, no?

> Small, incremental changes to large objects. Repeatedly polling for a large object is expensive, especially when most of the object's fields rarely change. Instead, you can fetch the object's initial state with a query, and your server can proactively push updates to individual fields as they occur.

> Low-latency, real-time updates. For example, a chat application's client wants to receive new messages as soon as they're available.

In any case, I'm also not suggesting we do this now, but I think it's an improvement we should be aware of as I think (if it's the same in prod as locally) a user would notice.

**Comment by jakubcolony** [comment] 2023-04-18 09:09
> Small, incremental changes to large objects.

I don't think this is the case. We refetch large objects (actions) that either don't change or are entirely new. It's not as if we're just querying for one field of those actions.

> Low-latency, real-time updates. For example, a chat application's client wants to receive new messages as soon as they're available.

Is this justifiable for the actions list? Have a look at other web apps, they very rarely use websockets until there's a true requirement for real time data. Queries are fire-and-forget whereas websockets need to maintain a constant connection, it's a big cost that I think needs a very good justification. They put overheads on both server and client (e.g., we'll somehow need to reconcile the existing actions with the incoming new ones). And using these alone is far from solving the problem; note that the Dapp already used them. They don't remove neither the need for the initial query, nor for making the full queries every time the sorting order changes.

It's not a problem without solution. But subscriptions don't sound right in this context. I think if it proves to be an issue, we'll need to find a balance between response times, showing potentially stale data, and the queries we make. For example, W
we're currently fetching the same action fields for both list and details page - surely something could be done around that.

It's great that you highlight this, as it was one of the biggest pain points in the Dapp.

**Comment by rdig** [comment] 2023-12-18 10:54
Closing as no longer relevant

**Closed by rdig** 2023-12-18 10:54 UTC
