### ISSUE TITLE
Token selection field broken on mobile.

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2804] opened 2024-07-30 08:44 UTC
## Steps to reproduce

1. Ensure the colony has at least 8 managed tokens.
2. Set your mobile screen size to iPhone SE: 375x667
3. Open up a new Transfer funds action.
4. Click on the token selection field.

## Expected behaviour

* You should be able to scroll through the list of managed tokens.

## Actual behaviour

* On mobile, the token select dropdown does not scroll and overflows the dropdown container.

![image](https://github.com/user-attachments/assets/82b9a27c-d946-47f7-898b-ccc7bd05e010)

**Comment by rdig** [comment] 2024-07-30 09:48
This is on `master` right? @iamsamgibbs can you investigate if this will be fixed by #2464 ?

**Comment by iamsamgibbs** [comment] 2024-07-30 11:06
The issue is also happening on 2464

<img width="379" alt="Screenshot 2024-07-30 at 12 05 24" src="https://github.com/user-attachments/assets/a443fc68-b23c-4816-ac8a-9e0ea5d159d8">

**Closed** 2024-08-15 20:53 UTC
Labels: bug
