### ISSUE TITLE
Staged payment is missing in Payment actions

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#3480] opened 2024-10-25 15:43 UTC
## Steps to reproduce

1. Ensure you have the Staged payment extension installed.
2. Click on the Make Payment main nav item.
3. Note the payment options available.

## Expected behaviour

* The Staged payment action should be included in the list if the Staged payment extension is installed.

## Actual behaviour

* No Staged payment action is showing in Payment category, but is showing in the action list.

![image](https://github.com/user-attachments/assets/b03003f2-f795-48a1-bbf6-425b5e5d1e62)

![image](https://github.com/user-attachments/assets/bde6fc8d-164c-4e39-8add-5c5257a3c4ea)

**Comment by rdig** [comment] 2024-10-28 15:54
This is a duplicate of #3441

Closing it in favor of that

**Closed by rdig** 2024-10-28 15:54 UTC
Labels: bug
