### ISSUE TITLE
UI gets stuck if Advanced payment is not ready

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyCDapp#2964] opened 2024-08-16 16:02 UTC
## Steps to reproduce

This one was hard to reproduce, but definitely happened more than once today as of my screenshots. Once in production and once in local dev.

1. Create a new Advanced payment action.
2. Click the "Confirm details" button to lock the Advanced payment.
3. Note if it goes through, or get's stuck in a loading state with errors in the console.

## Expected behaviour

* There should be a validation error at the button in the UI if the payment is not ready.
* The button should stay in it's loading state until the advanced payment is ready.

## Actual behaviour

* The UI gets stuck when trying to lock if the advanced payment is not ready.

![image](https://github.com/user-attachments/assets/8d2befd7-335c-4e09-a783-19336ec826a5)

![image](https://github.com/user-attachments/assets/560b4fd9-b0ea-4a4d-b38c-70000a764f24)

**Comment by jakubcolony** [comment] 2024-08-21 13:14
@arrenv looks like a duplicate of #2957

**Closed** 2024-08-21 13:14 UTC
Labels: bug
