### ISSUE TITLE
Wire in Edit Colony Details dialog with motion components and saga

### ISSUE THREAD

**Issue by ArmandoGraterol** [JoinColony/colonyCDapp#481] opened 2023-04-26 16:40 UTC
With the voting reputation extension enabled, the dialog should now have:
- Motion domain selector (**Disabled** as you can only create this motion in Root).
- Force toggle.
- A "Not enough reputation" message if there's no reputation in the motion domain selected.
- The submit button should change to "Create Motion".
- Of course, on submit it should take you to the motion's page.

How this dialog with the extension enabled looks like in the Dapp:
![Image](https://user-images.githubusercontent.com/18473896/234644577-fef191ee-5fd9-4d93-801a-27d3685b980d.png)

**Comment by jakubcolony** [comment] 2023-04-27 22:32
Looks like a duplicate of #433 ?

**Comment by jakubcolony** [comment] 2023-05-04 09:22
Closing this as duplicate of #433

**Closed by jakubcolony** 2023-05-04 09:22 UTC
